In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('social_media_sleep_stress_productivity_11000.csv')
df.head()

,user_id,age,daily_screen_time_hours,social_media_hours,sleep_hours,exercise_minutes,study_work_hours,productivity_score,stress_level,platform
0,1,44,2.39,1.93,8.46,61,3.73,33.86,Low,YouTube
1,2,30,7.22,5.24,7.34,28,6.80,85.32,Low,YouTube
2,3,23,2.56,4.64,4.69,8,4.47,60.07,High,YouTube
3,4,36,8.75,4.89,5.05,53,9.53,36.46,Medium,LinkedIn
4,5,34,10.96,2.77,7.12,83,7.01,32.93,Medium,Instagram

In [ ]:
# Coulmn data types
df.dtypes

user_id                      int64
age                          int64
daily_screen_time_hours    float64
social_media_hours         float64
sleep_hours                float64
exercise_minutes             int64
study_work_hours           float64
productivity_score         float64
stress_level                   str
platform                       str
dtype: object

In [9]:
df.select_dtypes(include=['number'])

,user_id,age,daily_screen_time_hours,social_media_hours,sleep_hours,exercise_minutes,study_work_hours,productivity_score
0,1,44,2.39,1.93,8.46,61,3.73,33.86
1,2,30,7.22,5.24,7.34,28,6.80,85.32
2,3,23,2.56,4.64,4.69,8,4.47,60.07
3,4,36,8.75,4.89,5.05,53,9.53,36.46
4,5,34,10.96,2.77,7.12,83,7.01,32.93
...,...,...,...,...,...,...,...,...
10995,10996,27,8.25,7.69,6.40,82,2.08,23.52
10996,10997,35,8.55,6.88,6.43,62,6.67,48.11
10997,10998,38,1.25,6.66,7.21,104,7.72,14.62
10998,10999,45,1.59,4.02,3.50,106,8.86,39.40
10999,11000,45,6.86,2.09,7.48,33,6.24,38.82

In [8]:
df.select_dtypes(include=['object', 'category'])

C:\Users\VikasKimathi\AppData\Local\Temp\ipykernel_5440\2412023022.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=['object', 'category'])

      stress_level   platform
0              Low    YouTube
1              Low    YouTube
2             High    YouTube
3           Medium   LinkedIn
4           Medium  Instagram
...            ...        ...
10995          Low   LinkedIn
10996         High    YouTube
10997          Low  Instagram
10998          Low   Snapchat
10999       Medium    Twitter

[11000 rows x 2 columns]

In [10]:
df.isnull().sum()

user_id                    0
age                        0
daily_screen_time_hours    0
social_media_hours         0
sleep_hours                0
exercise_minutes           0
study_work_hours           0
productivity_score         0
stress_level               0
platform                   0
dtype: int64

In [11]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10995    False
10996    False
10997    False
10998    False
10999    False
Length: 11000, dtype: bool

In [12]:
df['age'].value_counts().head(10)

age
41    371
28    370
32    367
38    354
43    344
31    343
44    338
37    333
33    332
39    331
Name: count, dtype: int64

In [13]:
df['stress_level'].value_counts().head()

stress_level
Low       3715
Medium    3681
High      3604
Name: count, dtype: int64